# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f9884d5b356b522125f84c45e1964da9739fa165abdcf8f7e09f81cee1bd8f39962708bd1905d140946b83c3a49cc2882bd8ef3ecb76e255fb16f6d723f913

test:
  secret_key_base: a86e5a3a939081c4eeffededb92e818043fbfb1477cfa8582ee5d6959d925e44fbd0e7e1f53e29bf89de2058120774325829266746588b3c27c6d4ee870b1758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
